# Mapping exact des tags Cobblemon → biomes réels
# Source : Wiki officiel Cobblemon (données vérifiées)
# Clés = tags FR utilisés dans la BDD / Valeurs = biomes réels par mod

BIOME_MAP = {
    "Aride": [
        {"biome": "All Sandy biomes", "mod": "Cobblemon"},
        {"biome": "All Savanna biomes", "mod": "Cobblemon"},
    ],
    "Terres arides": [  # Badlands
        {"biome": "All vanilla Badlands biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Ashen Savanna", "mod": "Terralith"},
        {"biome": "Red Oasis", "mod": "Terralith"},
        {"biome": "Warped Mesa", "mod": "Terralith"},
        {"biome": "White Mesa", "mod": "Terralith"},
        {"biome": "Danakil Desert", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Plage": [  # Beach
        {"biome": "All vanilla Beach biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Guelta", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Sand Dunes", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Grotte": [  # Cave
        {"biome": "Dripstone Caves", "mod": "Vanilla Minecraft"},
        {"biome": "Lush Caves", "mod": "Vanilla Minecraft"},
        {"biome": "Andesite Caves", "mod": "Terralith"},
        {"biome": "Desert Caves", "mod": "Terralith"},
        {"biome": "Diorite Caves", "mod": "Terralith"},
        {"biome": "Fungal Caves", "mod": "Terralith"},
        {"biome": "Granite Caves", "mod": "Terralith"},
        {"biome": "Infested Caves", "mod": "Terralith"},
        {"biome": "Thermal Caves", "mod": "Terralith"},
        {"biome": "Underground Jungle", "mod": "Terralith"},
    ],
    "Côte": [  # Coast
        {"biome": "Stony Shore", "mod": "Vanilla Minecraft"},
        {"biome": "All Beach biomes", "mod": "Cobblemon"},
        {"biome": "Basalt Cliffs", "mod": "Terralith"},
        {"biome": "Granite Cliffs", "mod": "Terralith"},
        {"biome": "White Cliffs", "mod": "Terralith"},
        {"biome": "Calcite Coast", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Coastal Mangroves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Cold Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Cold Stony Shore", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Deepslate Shore", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frigid Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frozen Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Gravelly Beach", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Icy Shore", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mediterranean Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Temperate Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Warm Stony Shore", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Froid": [  # Cold
        {"biome": "All Cold Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Freezing biomes", "mod": "Cobblemon"},
        {"biome": "All Peak biomes", "mod": "Cobblemon"},
        {"biome": "All Taiga biomes", "mod": "Cobblemon"},
        {"biome": "All Tundra biomes", "mod": "Cobblemon"},
        {"biome": "All BYG Cold biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Berry Bog", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Abysses sombres": [  # Deep Dark
        {"biome": "Deep Dark", "mod": "Vanilla Minecraft"},
        {"biome": "Crystal Caves", "mod": "Terralith"},
        {"biome": "Deep Caves", "mod": "Terralith"},
        {"biome": "Frostfire Caves", "mod": "Terralith"},
        {"biome": "Mantle Caves", "mod": "Terralith"},
        {"biome": "Tuff Caves", "mod": "Terralith"},
        {"biome": "Deep Dark Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Deep Dark Incursion", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Grand océan": [  # Deep Ocean
        {"biome": "All vanilla Deep Ocean biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Deep Icy Ocean", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Désert": [  # Desert
        {"biome": "Desert", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG desert biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Ancient Sands", "mod": "Terralith"},
        {"biome": "Desert Canyon", "mod": "Terralith"},
        {"biome": "Desert Caves", "mod": "Terralith"},
        {"biome": "Desert Oasis", "mod": "Terralith"},
        {"biome": "Desert Spires", "mod": "Terralith"},
        {"biome": "Lush Desert", "mod": "Terralith"},
        {"biome": "Red Oasis", "mod": "Terralith"},
        {"biome": "All Wythers' desert biomes", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Badlands Desert", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Desert Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Kwongan Heath", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Outback Desert", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Red Desert", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Sandy Jungle", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Stalactites": [  # Dripstone
        {"biome": "Dripstone Caves", "mod": "Vanilla Minecraft"},
        {"biome": "Fractured Savanna", "mod": "Terralith"},
        {"biome": "Stony Spires", "mod": "Terralith"},
        {"biome": "Fungous Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lichenous Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lush Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lush Fungous Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mossy Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Floral": [  # Floral
        {"biome": "Cherry Grove", "mod": "Vanilla Minecraft"},
        {"biome": "Flower Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Meadow", "mod": "Vanilla Minecraft"},
        {"biome": "Sunflower Plains", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Floral biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Amaranth Fields", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Allium Fields", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Rose Fields", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Skyris Vale", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Cherry Blossom Forest", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Orchard", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Blooming Plateau", "mod": "Terralith"},
        {"biome": "Blooming Valley", "mod": "Terralith"},
        {"biome": "Lavender Forest", "mod": "Terralith"},
        {"biome": "Lavender Valley", "mod": "Terralith"},
        {"biome": "Sakura Grove", "mod": "Terralith"},
        {"biome": "Sakura Valley", "mod": "Terralith"},
        {"biome": "Autumnal Flower Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Flowering Pantanal", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jacaranda Savanna", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lapacho Plains", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Sakura Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Spring Flower Fields", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Spring Flower Forest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Forêt": [  # Forest
        {"biome": "All vanilla Forest biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Cherry Grove", "mod": "Vanilla Minecraft"},
        {"biome": "Alpha Islands", "mod": "Terralith"},
        {"biome": "Alpha Islands Winter", "mod": "Terralith"},
        {"biome": "Blooming Valley", "mod": "Terralith"},
        {"biome": "Forested Highlands", "mod": "Terralith"},
        {"biome": "Lavender Forest", "mod": "Terralith"},
        {"biome": "Lavender Valley", "mod": "Terralith"},
        {"biome": "Mirage Isles", "mod": "Terralith"},
        {"biome": "Sakura Grove", "mod": "Terralith"},
        {"biome": "Sakura Valley", "mod": "Terralith"},
        {"biome": "Temperate Highlands", "mod": "Terralith"},
        {"biome": "Dry Tropical Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Birch Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Boreal Forest Red", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Boreal Forest Yellow", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Subtropical Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tangled Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Glacial": [  # Freezing (tag large, englobe tout le froid extrême)
        {"biome": "Frozen River", "mod": "Vanilla Minecraft"},
        {"biome": "Jagged Peaks", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Beach", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Plains", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Slopes", "mod": "Vanilla Minecraft"},
        {"biome": "All Frozen Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Glacial biomes", "mod": "Cobblemon"},
        {"biome": "All Snowy Forest biomes", "mod": "Cobblemon"},
        {"biome": "All BYG Snowy biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Cardinal Tundra", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Emerald Peaks", "mod": "Terralith"},
        {"biome": "Scarlet Mountains", "mod": "Terralith"},
        {"biome": "Skylands Winter", "mod": "Terralith"},
        {"biome": "Snowy Badlands", "mod": "Terralith"},
        {"biome": "Crimson Tundra", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frozen Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Bog", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Canyon", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Peaks", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Tundra", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Eau douce": [  # Freshwater
        {"biome": "All River biomes", "mod": "Cobblemon"},
        {"biome": "All Swamp biomes", "mod": "Cobblemon"},
        {"biome": "Desert Lakes", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Guelta", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest River", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Océan gelé": [  # Frozen Ocean
        {"biome": "Deep Frozen Ocean", "mod": "Vanilla Minecraft"},
        {"biome": "Frozen Ocean", "mod": "Vanilla Minecraft"},
        {"biome": "Frozen Cliffs", "mod": "Terralith"},
        {"biome": "Deep Icy Ocean", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Icy Ocean", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Glaciaire": [  # Glacial (pics et glaces spécifiques)
        {"biome": "Frozen Peaks", "mod": "Vanilla Minecraft"},
        {"biome": "Ice Spikes", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Icy biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Frostfire Caves", "mod": "Terralith"},
        {"biome": "Frozen Cliffs", "mod": "Terralith"},
        {"biome": "Glacial Chasm", "mod": "Terralith"},
        {"biome": "Glacial Cliffs", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Ice Cap", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Icy Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frozen Island", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Prairie": [  # Grassland
        {"biome": "All Plains biomes", "mod": "Cobblemon"},
        {"biome": "All Savanna biomes", "mod": "Cobblemon"},
    ],
    "Hautes terres": [  # Highlands
        {"biome": "Meadow", "mod": "Vanilla Minecraft"},
        {"biome": "Alpine Highlands", "mod": "Terralith"},
        {"biome": "Arid Highlands", "mod": "Terralith"},
        {"biome": "Blooming Plateau", "mod": "Terralith"},
        {"biome": "Highlands", "mod": "Terralith"},
        {"biome": "Bamboo Jungle Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Eucalyptus Deanei Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Forested Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Huangshan Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Highland Tropical Rainforest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jade Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Wistman Woods", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Collines": [  # Hills
        {"biome": "All vanilla Hills biomes", "mod": "Vanilla Minecraft"},
        {"biome": "All Highlands biomes", "mod": "Cobblemon"},
        {"biome": "Blooming Valley", "mod": "Terralith"},
        {"biome": "Forested Highlands", "mod": "Terralith"},
        {"biome": "Lavender Valley", "mod": "Terralith"},
        {"biome": "Lush Valley", "mod": "Terralith"},
        {"biome": "Moonlight Valley", "mod": "Terralith"},
        {"biome": "Sakura Valley", "mod": "Terralith"},
        {"biome": "Savanna Slopes", "mod": "Terralith"},
        {"biome": "Temperate Highlands", "mod": "Terralith"},
        {"biome": "Yosemite Lowlands", "mod": "Terralith"},
        {"biome": "Autumnal Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Ayers Rock", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Icy Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Old Growth Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Temperate Rainforest Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Windswept Jungle", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Île": [  # Island
        {"biome": "Mushroom Fields", "mod": "Vanilla Minecraft"},
        {"biome": "All Tropical Island biomes", "mod": "Cobblemon"},
        {"biome": "Lush Stacks", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Alpha Islands", "mod": "Terralith"},
        {"biome": "Alpha Islands Winter", "mod": "Terralith"},
        {"biome": "Mirage Isles", "mod": "Terralith"},
        {"biome": "Warped Mesa", "mod": "Terralith"},
        {"biome": "Cold Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Desert Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frigid Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frozen Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jungle Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mediterranean Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mediterranean Island Thermal Springs", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mushroom Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Temperate Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Island", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Jungle": [
        {"biome": "All vanilla Jungle biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Underground Jungle", "mod": "Terralith"},
        {"biome": "Dripleaf Swamp", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Eucalyptus Deanei Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Highland Tropical Rainforest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Humid Tropical Grassland", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jungle Canyon", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Subtropical Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Subtropical Forest Edge", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Subtropical Grassland", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest Canyon", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Grassland", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Rainforest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Océan tiède": [  # Lukewarm Ocean
        {"biome": "Deep Lukewarm Ocean", "mod": "Vanilla Minecraft"},
        {"biome": "Lukewarm Ocean", "mod": "Vanilla Minecraft"},
    ],
    "Luxuriant": [  # Lush
        {"biome": "Lush Caves", "mod": "Vanilla Minecraft"},
        {"biome": "Lush Stacks", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Underground Jungle", "mod": "Terralith"},
        {"biome": "Lichenous Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lichenous Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lush Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lush Fungous Dripstone Caves", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lush Shroom Caves", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Magique": [  # Magical
        {"biome": "Dark Forest", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Magical biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Skyris Vale", "mod": "Oh The Biomes You'll Go"},
        {"biome": "All Wythers' Dark Forest biomes", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Lantern River", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mushroom Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Amethyst Canyon", "mod": "Terralith"},
        {"biome": "Amethyst Rainforest", "mod": "Terralith"},
        {"biome": "Mirage Isles", "mod": "Terralith"},
        {"biome": "Moonlight Grove", "mod": "Terralith"},
        {"biome": "Moonlight Valley", "mod": "Terralith"},
    ],
    "Montagne": [  # Mountain
        {"biome": "All vanilla Mountain biomes", "mod": "Vanilla Minecraft"},
        {"biome": "All Hill biomes", "mod": "Cobblemon"},
        {"biome": "Stony Spires", "mod": "Terralith"},
        {"biome": "Volcanic Peaks", "mod": "Terralith"},
        {"biome": "Windswept Spires", "mod": "Terralith"},
        {"biome": "Yosemite Cliffs", "mod": "Terralith"},
        {"biome": "Tibesti Mountains", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Volcano", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tsingy Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Volcano", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Champignon": [  # Mushroom
        {"biome": "Dark Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Mushroom Fields", "mod": "Vanilla Minecraft"},
        {"biome": "Fungal Caves", "mod": "Terralith"},
        {"biome": "Mirage Isles", "mod": "Terralith"},
        {"biome": "Ancient Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Deep Dark Incursion", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Océan": [  # Ocean
        {"biome": "All vanilla Ocean biomes", "mod": "Vanilla Minecraft"},
        {"biome": "All Coast biomes", "mod": "Cobblemon"},
        {"biome": "All Cold Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Deep Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Frozen Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Lukewarm Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Warm Ocean biomes", "mod": "Cobblemon"},
    ],
    "Sommet": [  # Peak
        {"biome": "Frozen Peaks", "mod": "Vanilla Minecraft"},
        {"biome": "Jagged Peaks", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Slopes", "mod": "Vanilla Minecraft"},
        {"biome": "Stony Peaks", "mod": "Vanilla Minecraft"},
        {"biome": "Emerald Peaks", "mod": "Terralith"},
        {"biome": "Rocky Mountains", "mod": "Terralith"},
        {"biome": "Scarlet Mountains", "mod": "Terralith"},
        {"biome": "Windswept Spires", "mod": "Terralith"},
        {"biome": "Andesite Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Aspen Crags", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Plaines": [  # Plains
        {"biome": "Plains", "mod": "Vanilla Minecraft"},
        {"biome": "Sunflower Plains", "mod": "Vanilla Minecraft"},
        {"biome": "All Highlands biomes", "mod": "Cobblemon"},
        {"biome": "All BYG Plains biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Brushland", "mod": "Terralith"},
        {"biome": "Steppe", "mod": "Terralith"},
        {"biome": "Valley Clearing", "mod": "Terralith"},
        {"biome": "Berry Bog", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Cool Forest Edge", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Dry Tropical Grassland", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Forest Edge", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Spring Flower Fields", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Subtropical Forest Edge", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Grassland", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Plateau": [
        {"biome": "Savanna Plateau", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Plateau biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Ayers Rock", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Rivière": [  # River
        {"biome": "All vanilla River biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Warm River", "mod": "Vanilla Minecraft"},
        {"biome": "Guelta", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest River", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Sel": [  # Salt
        {"biome": "Calcite Caverns", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Calcite Coast", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mediterranean Island Thermal Spring", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Salt Lakes Pink", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Salt Lakes Turquoise", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Salt Lakes White", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Sableux": [  # Sandy
        {"biome": "All Badlands biomes", "mod": "Cobblemon"},
        {"biome": "All Desert biomes", "mod": "Cobblemon"},
        {"biome": "All BYG Sandy biomes", "mod": "Oh The Biomes You'll Go"},
    ],
    "Savane": [  # Savanna
        {"biome": "All vanilla Savanna biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Arid Highlands", "mod": "Terralith"},
        {"biome": "Ashen Savanna", "mod": "Terralith"},
        {"biome": "Brushland", "mod": "Terralith"},
        {"biome": "Desert Oasis", "mod": "Terralith"},
        {"biome": "Fractured Savanna", "mod": "Terralith"},
        {"biome": "Hot Shrubland", "mod": "Terralith"},
        {"biome": "Red Oasis", "mod": "Terralith"},
        {"biome": "Savanna Badlands", "mod": "Terralith"},
        {"biome": "Savanna Slopes", "mod": "Terralith"},
        {"biome": "Shrublands", "mod": "Terralith"},
        {"biome": "Granite Canyon", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest Canyon", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Forest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Ciel": [  # Sky
        {"biome": "Skylands Autumn", "mod": "Terralith"},
        {"biome": "Skylands Spring", "mod": "Terralith"},
        {"biome": "Skylands Summer", "mod": "Terralith"},
        {"biome": "Skylands Winter", "mod": "Terralith"},
    ],
    "Forêt enneigée": [  # Snowy Forest
        {"biome": "Grove", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Taiga", "mod": "Vanilla Minecraft"},
        {"biome": "Alpha Islands Winter", "mod": "Terralith"},
        {"biome": "Alpine Grove", "mod": "Terralith"},
        {"biome": "Ice Marsh", "mod": "Terralith"},
        {"biome": "Siberian Grove", "mod": "Terralith"},
        {"biome": "Snowy Maple Forest", "mod": "Terralith"},
        {"biome": "Snowy Shield", "mod": "Terralith"},
        {"biome": "Wintry Forest", "mod": "Terralith"},
        {"biome": "Wintry Lowlands", "mod": "Terralith"},
        {"biome": "Deep Snowy Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Huangshan Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jade Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Fen", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Effrayant": [  # Spooky
        {"biome": "Dark Forest", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Spooky biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Ebony Woods", "mod": "Oh The Biomes You'll Go"},
        {"biome": "All Wythers' Dark Forest biomes", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Ancient Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Bayou", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tangled Forest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Marais": [  # Swamp
        {"biome": "Mangrove Swamp", "mod": "Vanilla Minecraft"},
        {"biome": "Swamp", "mod": "Vanilla Minecraft"},
        {"biome": "All BYG Swamp biomes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "All Wythers' Swamp biomes", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Billabong", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Ice Marsh", "mod": "Terralith"},
        {"biome": "Orchid Swamp", "mod": "Terralith"},
    ],
    "Taïga": [  # Taiga
        {"biome": "All vanilla Taiga biomes", "mod": "Vanilla Minecraft"},
        {"biome": "Grove", "mod": "Vanilla Minecraft"},
        {"biome": "Alpine Grove", "mod": "Terralith"},
        {"biome": "Haze Mountain", "mod": "Terralith"},
        {"biome": "Ice Marsh", "mod": "Terralith"},
        {"biome": "Moonlight Grove", "mod": "Terralith"},
        {"biome": "Moonlight Valley", "mod": "Terralith"},
        {"biome": "Shield Clearing", "mod": "Terralith"},
        {"biome": "Siberian Grove", "mod": "Terralith"},
        {"biome": "Siberian Taiga", "mod": "Terralith"},
        {"biome": "Snowy Maple Forest", "mod": "Terralith"},
        {"biome": "Snowy Shield", "mod": "Terralith"},
        {"biome": "Wintry Lowlands", "mod": "Terralith"},
        {"biome": "Ancient Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Birch Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Boreal Forest Red", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Boreal Forest Yellow", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Cold Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Deep Snowy Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Fen", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Flooded Temperate Rainforest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Forested Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Huangshan Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Jade Highlands", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Larch Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Old Growth Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Old Growth Taiga Swamp", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Pine Barrens", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Temperate Rainforest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Temperate Rainforest Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Tempéré": [  # Temperate
        {"biome": "All Forest biomes", "mod": "Cobblemon"},
        {"biome": "All Plains biomes", "mod": "Cobblemon"},
    ],
    "Thermal": [
        {"biome": "Caldera", "mod": "Terralith"},
        {"biome": "Thermal Caves", "mod": "Terralith"},
        {"biome": "Yellowstone", "mod": "Terralith"},
        {"biome": "Calcite Caverns", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Mediterranean Island Thermal Springs", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Thermal Taiga", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tibesti Mountains", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Danakil Desert", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Île tropicale": [  # Tropical Island
        {"biome": "Tropical Beach", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Volcano", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Toundra": [  # Tundra
        {"biome": "Ice Spikes", "mod": "Vanilla Minecraft"},
        {"biome": "Snowy Plains", "mod": "Vanilla Minecraft"},
        {"biome": "Cardinal Tundra", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Cold Shrubland", "mod": "Terralith"},
        {"biome": "Gravel Desert", "mod": "Terralith"},
        {"biome": "Rocky Shrubland", "mod": "Terralith"},
        {"biome": "Snowy Badlands", "mod": "Terralith"},
        {"biome": "Yellowstone", "mod": "Terralith"},
        {"biome": "Crimson Tundra", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Frigid Island", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Ice Cap", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Icy Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Snowy Tundra", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tundra", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Volcanique": [  # Volcanic
        {"biome": "Mantle Caves", "mod": "Terralith"},
        {"biome": "Volcanic Crater", "mod": "Terralith"},
        {"biome": "Volcanic Peaks", "mod": "Terralith"},
        {"biome": "Icy Volcano", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Tropical Volcano", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Volcano", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Volcanic Chamber", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Volcanic Crater", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Océan chaud": [  # Warm Ocean
        {"biome": "Warm Ocean", "mod": "Vanilla Minecraft"},
        {"biome": "Lush Stacks", "mod": "Terralith"},
    ],
    "Monde de surface": [  # Overworld
        {"biome": "All vanilla Overworld biomes", "mod": "Vanilla Minecraft"},
        {"biome": "All Arid biomes", "mod": "Cobblemon"},
        {"biome": "All Cave biomes", "mod": "Cobblemon"},
        {"biome": "All Coast biomes", "mod": "Cobblemon"},
        {"biome": "All Cold biomes", "mod": "Cobblemon"},
        {"biome": "All Deep Dark biomes", "mod": "Cobblemon"},
        {"biome": "All Floral biomes", "mod": "Cobblemon"},
        {"biome": "All Forest biomes", "mod": "Cobblemon"},
        {"biome": "All Freshwater biomes", "mod": "Cobblemon"},
        {"biome": "All Grassland biomes", "mod": "Cobblemon"},
        {"biome": "All Highlands biomes", "mod": "Cobblemon"},
        {"biome": "All Island biomes", "mod": "Cobblemon"},
        {"biome": "All Jungle biomes", "mod": "Cobblemon"},
        {"biome": "All Magical biomes", "mod": "Cobblemon"},
        {"biome": "All Mountain biomes", "mod": "Cobblemon"},
        {"biome": "All Mushroom biomes", "mod": "Cobblemon"},
        {"biome": "All Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Sky biomes", "mod": "Cobblemon"},
        {"biome": "All Spooky biomes", "mod": "Cobblemon"},
        {"biome": "All Temperate biomes", "mod": "Cobblemon"},
        {"biome": "All Thermal biomes", "mod": "Cobblemon"},
        {"biome": "All Volcanic biomes", "mod": "Cobblemon"},
    ],
    "Fin": [  # End
        {"biome": "All vanilla End biomes", "mod": "Vanilla Minecraft"},
    ],
    "Nether": [
        {"biome": "All vanilla Nether biomes", "mod": "Vanilla Minecraft"},
    ],
    "Nether basaltique": [  # Nether Basalt
        {"biome": "Basalt Deltas", "mod": "Vanilla Minecraft"},
        {"biome": "Blackstone Shales", "mod": "Cinderscapes"},
        {"biome": "Ash Barrens", "mod": "Incendium"},
        {"biome": "Volcanic Deltas", "mod": "Incendium"},
        {"biome": "Withered Forest", "mod": "Incendium"},
    ],
    "Nether cramoisi": [  # Nether Crimson
        {"biome": "Crimson Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Crimson Glowing Woods", "mod": "BetterNether"},
        {"biome": "Crimson Pinewood", "mod": "BetterNether"},
        {"biome": "Nether Swampland", "mod": "BetterNether"},
        {"biome": "Nether Swampland Terraces", "mod": "BetterNether"},
        {"biome": "Crimson Gardens", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Whistling Woods", "mod": "Gardens of the Dead"},
    ],
    "Désert du Nether": [  # Nether Desert
        {"biome": "Soul Sand Valley", "mod": "Vanilla Minecraft"},
        {"biome": "Gravel Desert", "mod": "BetterNether"},
        {"biome": "Quartz Desert", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Warped Desert", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Infernal Dunes", "mod": "Incendium"},
        {"biome": "Weeping Valley", "mod": "Incendium"},
    ],
    "Forêt du Nether": [  # Nether Forest
        {"biome": "Nether Jungle", "mod": "BetterNether"},
        {"biome": "Nether Swampland", "mod": "BetterNether"},
        {"biome": "Nether Swampland Terraces", "mod": "BetterNether"},
        {"biome": "Weeping Mire", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Withering Woods", "mod": "Oh The Biomes You'll Go"},
    ],
    "Nether gelé": [  # Nether Frozen
        {"biome": "Subzero Hypogeal", "mod": "Oh The Biomes You'll Go"},
    ],
    "Nether fongique": [  # Nether Fungus
        {"biome": "Crimson Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Warped Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Crimson Glowing Woods", "mod": "BetterNether"},
        {"biome": "Crimson Pinewood", "mod": "BetterNether"},
        {"biome": "Mushroom Forest", "mod": "BetterNether"},
        {"biome": "Mushroom Forest Edge", "mod": "BetterNether"},
        {"biome": "Old Fungiwoods", "mod": "BetterNether"},
        {"biome": "Old Warped Woods", "mod": "BetterNether"},
        {"biome": "Crimson Gardens", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Embur Bog", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Glowstone Garden", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Wailing Garth", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Luminous Grove", "mod": "Cinderscapes"},
        {"biome": "Whistling Woods", "mod": "Gardens of the Dead"},
        {"biome": "Soulblight Forest", "mod": "Gardens of the Dead"},
        {"biome": "Inverted Forest", "mod": "Incendium"},
    ],
    "Montagne du Nether": [  # Nether Mountain
        {"biome": "Basalt Deltas", "mod": "Vanilla Minecraft"},
        {"biome": "Volcanic Deltas", "mod": "Incendium"},
    ],
    "Végétation du Nether": [  # Nether Overgrowth
        {"biome": "Bone Reef", "mod": "BetterNether"},
        {"biome": "Nether Grasslands", "mod": "BetterNether"},
        {"biome": "Soul Plain", "mod": "BetterNether"},
        {"biome": "Sulfuric Bone Reef", "mod": "BetterNether"},
        {"biome": "Sythian Torrids", "mod": "Oh The Biomes You'll Go"},
    ],
    "Quartz du Nether": [  # Nether Quartz
        {"biome": "Quartz Desert", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Quartz Cavern", "mod": "Cinderscapes"},
        {"biome": "Quartz Flats", "mod": "Incendium"},
    ],
    "Nether feu de l'Âme": [  # Nether Soul Fire
        {"biome": "Soul Sand Valley", "mod": "Vanilla Minecraft"},
        {"biome": "Subzero Hypogeal", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Warped Desert", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Quartz Flats", "mod": "Incendium"},
        {"biome": "Weeping Valley", "mod": "Incendium"},
    ],
    "Nether sable de l'Âme": [  # Nether Soul Sand
        {"biome": "Soul Sand Valley", "mod": "Vanilla Minecraft"},
        {"biome": "Soul Plain", "mod": "BetterNether"},
        {"biome": "Wart Forest", "mod": "BetterNether"},
        {"biome": "Wart Forest Edge", "mod": "BetterNether"},
        {"biome": "Wailing Garth", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Warped Desert", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Ashy Shoals", "mod": "Cinderscapes"},
        {"biome": "Blackstone Shales", "mod": "Cinderscapes"},
        {"biome": "Soulblight Forest", "mod": "Gardens of the Dead"},
        {"biome": "Weeping Valley", "mod": "Incendium"},
    ],
    "Nether toxique": [  # Nether Toxic
        {"biome": "Brimstone Caverns", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Wailing Garth", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Toxic Heap", "mod": "Incendium"},
    ],
    "Nether distordu": [  # Nether Warped
        {"biome": "Warped Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Nether Jungle", "mod": "BetterNether"},
        {"biome": "Old Warped Woods", "mod": "BetterNether"},
        {"biome": "Wailing Garth", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Warped Desert", "mod": "Oh The Biomes You'll Go"},
    ],
    "Terres dévastées du Nether": [  # Nether Wasteland
        {"biome": "Nether Wastes", "mod": "Vanilla Minecraft"},
        {"biome": "Magma Land", "mod": "BetterNether"},
        {"biome": "Poor Nether Grasslands", "mod": "BetterNether"},
        {"biome": "Brimstone Caverns", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Magma Wastes", "mod": "Oh The Biomes You'll Go"},
        {"biome": "Ashy Shoals", "mod": "Cinderscapes"},
        {"biome": "Quartz Cavern", "mod": "Cinderscapes"},
        {"biome": "Ash Barrens", "mod": "Incendium"},
        {"biome": "Toxic Heap", "mod": "Incendium"},
    ],
    "Bumblezone": [
        {"biome": "Hive Pillar", "mod": "The Bumblezone"},
        {"biome": "Hive Wall", "mod": "The Bumblezone"},
        {"biome": "Pollinated Fields", "mod": "The Bumblezone"},
        {"biome": "Pollinated Pillar", "mod": "The Bumblezone"},
        {"biome": "Sugar Water Floor", "mod": "The Bumblezone"},
        {"biome": "Crystal Canyon", "mod": "The Bumblezone"},
        {"biome": "Floral Meadow", "mod": "The Bumblezone"},
        {"biome": "Howling Constructs", "mod": "The Bumblezone"},
    ],
    "Automne": [  # Autumn
        {"biome": "All Arid biomes", "mod": "Cobblemon"},
        {"biome": "All Cold Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Mountain biomes", "mod": "Cobblemon"},
        {"biome": "All Mushroom biomes", "mod": "Cobblemon"},
        {"biome": "All Taiga biomes", "mod": "Cobblemon"},
        {"biome": "Skylands Autumn", "mod": "Terralith"},
        {"biome": "Autumnal Birch Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Crags", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Flower Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Forest Edge", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Forest", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Plains", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Autumnal Swamp", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Harvest Fields", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Printemps": [  # Spring
        {"biome": "All Floral biomes", "mod": "Cobblemon"},
        {"biome": "All Lukewarm Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Magical biomes", "mod": "Cobblemon"},
        {"biome": "All Plains biomes", "mod": "Cobblemon"},
        {"biome": "Skylands Spring", "mod": "Terralith"},
        {"biome": "Spring Flower Fields", "mod": "Wythers' Overhauled Overworld"},
        {"biome": "Spring Flower Forest", "mod": "Wythers' Overhauled Overworld"},
    ],
    "Été": [  # Summer
        {"biome": "All Forest biomes", "mod": "Cobblemon"},
        {"biome": "All Jungle biomes", "mod": "Cobblemon"},
        {"biome": "All Lush biomes", "mod": "Cobblemon"},
        {"biome": "All Warm Ocean biomes", "mod": "Cobblemon"},
        {"biome": "All Swamp biomes", "mod": "Cobblemon"},
        {"biome": "Skylands Summer", "mod": "Terralith"},
    ],
    "Hiver": [  # Winter
        {"biome": "All Freezing biomes", "mod": "Cobblemon"},
        {"biome": "Skylands Winter", "mod": "Terralith"},
    ],
    "Dense": [
        {"biome": "Dark Forest", "mod": "Vanilla Minecraft"},
        {"biome": "Mangrove Swamp", "mod": "Vanilla Minecraft"},
        {"biome": "All Jungle biomes", "mod": "Cobblemon"},
    ],
    "Clairsemé": [  # Sparse
        {"biome": "All Arid biomes", "mod": "Cobblemon"},
        {"biome": "All Grassland biomes", "mod": "Cobblemon"},
        {"biome": "All Tundra biomes", "mod": "Cobblemon"},
    ],
    # Tags directs (sub-biomes utilisés comme tags dans la BDD)
    "Canyon de cristal":      [{"biome": "Crystal Canyon", "mod": "The Bumblezone"}],
    "Prairie fleurie":        [{"biome": "Floral Meadow", "mod": "The Bumblezone"}],
    "Champs pollinisés":      [{"biome": "Pollinated Fields", "mod": "The Bumblezone"}],
    "Constructions hurlantes":[{"biome": "Howling Constructs", "mod": "The Bumblezone"}],
    "Éther":                  [{"biome": "All Aether biomes", "mod": "Aether mod"}],
    "Bambou":                 [{"biome": "Bamboo Jungle", "mod": "Vanilla Minecraft"}, {"biome": "Bamboo Jungle Hills", "mod": "Vanilla Minecraft"}],
    "Boueux":                 [{"biome": "Mangrove Swamp", "mod": "Vanilla Minecraft"}],
    "Champs de champignons":  [{"biome": "Mushroom Fields", "mod": "Vanilla Minecraft"}],
    "Fleurs de cerisier":     [{"biome": "Cherry Grove", "mod": "Vanilla Minecraft"}, {"biome": "Sakura Grove", "mod": "Terralith"}, {"biome": "Sakura Valley", "mod": "Terralith"}],
    "Enneigé":                [{"biome": "Snowy Plains", "mod": "Vanilla Minecraft"}, {"biome": "Snowy Slopes", "mod": "Vanilla Minecraft"}, {"biome": "Ice Spikes", "mod": "Vanilla Minecraft"}, {"biome": "Grove", "mod": "Vanilla Minecraft"}, {"biome": "Snowy Taiga", "mod": "Vanilla Minecraft"}],
    "Plage enneigée":         [{"biome": "Snowy Beach", "mod": "Vanilla Minecraft"}],
    "Taïga enneigée":         [{"biome": "Snowy Taiga", "mod": "Vanilla Minecraft"}, {"biome": "Grove", "mod": "Vanilla Minecraft"}],
    "Rivière gelée":          [{"biome": "Frozen River", "mod": "Vanilla Minecraft"}],
    "Plaines de tournesols":  [{"biome": "Sunflower Plains", "mod": "Vanilla Minecraft"}],
    "Océan froid":            [{"biome": "Cold Ocean", "mod": "Vanilla Minecraft"}, {"biome": "Deep Cold Ocean", "mod": "Vanilla Minecraft"}],
    "Maquis":                 [{"biome": "Hot Shrubland", "mod": "Terralith"}, {"biome": "Shrublands", "mod": "Terralith"}, {"biome": "Cold Shrubland", "mod": "Terralith"}, {"biome": "Rocky Shrubland", "mod": "Terralith"}],
    "Forêt aérienne":         [{"biome": "Skylands Summer", "mod": "Terralith"}],
    "Bosquet aérien":         [{"biome": "Skylands Autumn", "mod": "Terralith"}],
    "Prairie aérienne":       [{"biome": "Skylands Spring", "mod": "Terralith"}],
    "Bois aérien":            [{"biome": "Skylands Winter", "mod": "Terralith"}],
    "Gouffre cristallin":     [{"biome": "Crystal Caves", "mod": "Terralith"}, {"biome": "Glacial Chasm", "mod": "Terralith"}],
    "Désert distordu":        [{"biome": "Warped Desert", "mod": "Oh The Biomes You'll Go"}],
}

MOD_COLORS = {
    "Vanilla Minecraft":              "#74b9ff",
    "Cobblemon":                      "#e8ff47",
    "Terralith":                      "#55efc4",
    "Wythers' Overhauled Overworld":  "#fd79a8",
    "Oh The Biomes You'll Go":        "#a29bfe",
    "BetterNether":                   "#ff7675",
    "Incendium":                      "#e17055",
    "Cinderscapes":                   "#d63031",
    "Gardens of the Dead":            "#00b894",
    "The Bumblezone":                 "#fdcb6e",
    "Aether mod":                     "#81ecec",
}

def get_real_biomes(tag_fr):
    """Retourne la liste des biomes réels pour un tag FR."""
    return BIOME_MAP.get(tag_fr, [{"biome": tag_fr, "mod": "Tag Cobblemon"}])

def expand_spawn_biomes(biomes_str):
    """Transforme 'Océan froid, Océan gelé, Toundra' en liste de dicts par tag."""
    if not biomes_str:
        return []
    return [{"tag": t.strip(), "biomes": get_real_biomes(t.strip())}
            for t in biomes_str.split(",") if t.strip()]

def get_mod_color(mod):
    return MOD_COLORS.get(mod, "#6a6a88")

# ------------------------------------------------------------------
# Carte inversée : biome réel → liste de tags FR qui le contiennent
# Utilisée pour filtrer par biome réel depuis l'index
# ------------------------------------------------------------------
def _build_reverse_map():
    reverse = {}
    for tag, biomes in BIOME_MAP.items():
        for b in biomes:
            key = b["biome"].lower()
            reverse.setdefault(key, []).append(tag)
    return reverse

REVERSE_BIOME_MAP = _build_reverse_map()

def get_tags_for_biome(real_biome_name):
    """Retourne les tags FR associés à un biome réel (recherche insensible à la casse)."""
    return REVERSE_BIOME_MAP.get(real_biome_name.lower(), [])

def get_all_real_biomes_sorted():
    """Retourne tous les biomes réels uniques triés, avec leur mod, sans doublons."""
    seen = {}
    for tag, biomes in BIOME_MAP.items():
        for b in biomes:
            key = b["biome"]
            if key not in seen:
                seen[key] = b["mod"]
    return sorted([{"biome": k, "mod": v} for k, v in seen.items()], key=lambda x: x["biome"])

def expand_biomes_by_mod(biomes_str):
    """
    Comme expand_spawn_biomes mais regroupe les biomes réels PAR MOD.
    Retourne : [{"tag": "...", "by_mod": {"Vanilla Minecraft": [...], "Terralith": [...], ...}}]
    """
    if not biomes_str:
        return []
    result = []
    for t in biomes_str.split(","):
        t = t.strip()
        if not t:
            continue
        real_biomes = get_real_biomes(t)
        by_mod = {}
        for b in real_biomes:
            mod = b["mod"]
            by_mod.setdefault(mod, []).append(b["biome"])
        result.append({"tag": t, "by_mod": by_mod})
    return result